# Form implementation generated from reading ui file 'QtDashboard/ui/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotLayout_ecg = QtWidgets.QHBoxLayout()
        self.plotLayout_ecg.setObjectName("plotLayout_ecg")
        self.label_ppg_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_ppg_2.setObjectName("label_ppg_2")
        self.plotLayout_ecg.addWidget(self.label_ppg_2)
        self.verticalLayout_2.addLayout(self.plotLayout_ecg)
        self.plotLayout_ppg = QtWidgets.QHBoxLayout()
        self.plotLayout_ppg.setObjectName("plotLayout_ppg")
        self.label_ppg = QtWidgets.QLabel(parent=self.groupBox)
        self.label_ppg.setObjectName("label_ppg")
        self.plotLayout_ppg.addWidget(self.label_ppg)
        self.verticalLayout_2.addLayout(self.plotLayout_ppg)
        self.plotLayout_gsr = QtWidgets.QHBoxLayout()
        self.plotLayout_gsr.setObjectName("plotLayout_gsr")
        self.label_gsr = QtWidgets.QLabel(parent=self.groupBox)
        self.label_gsr.setObjectName("label_gsr")
        self.plotLayout_gsr.addWidget(self.label_gsr)
        self.verticalLayout_2.addLayout(self.plotLayout_gsr)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Waveforms"))
        self.label_ppg_2.setText(_translate("Form", "ECG"))
        self.label_ppg.setText(_translate("Form", "PPG"))
        self.label_gsr.setText(_translate("Form", "GSR"))
